2019-07-01 15:03:52,156 Starting Bokeh server version 1.2.0 (running on Tornado 6.0.3)
2019-07-01 15:03:52,163 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:03:52,163 Starting Bokeh server with process id: 23741
2019-07-01 15:04:02,455 302 GET / (::1) 0.63ms
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}

Interrupted, shutting down
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190401.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190402.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190403.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190404.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190405.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190406.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190407.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190408.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190409.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190410.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190411.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190412.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190413.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190414.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190415.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190416.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190417.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190418.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190419.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190420.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190421.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190422.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190423.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190424.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190425.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190426.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190427.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190428.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190429.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_SA_D.001/2019/04/FLDAS_NOAH01_A_SA_D.A20190430.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190401.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190402.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190403.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190404.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190405.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190406.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190407.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190408.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190409.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190410.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190411.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190412.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190413.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190414.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190415.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190416.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190417.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190418.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190419.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190420.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190421.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190422.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190423.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190424.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method CachingFileManager.__del__ of CachingFileManager(<function _open_netcdf4_group at 0x7fab31551620>, '/home/hayley/data/mint/FLDAS/FLDAS_NOAH01_A_EA_D.001/2019/04/FLDAS_NOAH01_A_EA_D.A20190425.001.nc', CombinedLock([<SerializableLock: 45970af6-c4d2-4d7b-8a05-040f12880de9>, <SerializableLock: c2ab0386-be39-4be6-9f08-f3ecb8e17e40>]), mode='r', kwargs={'group': None, 'clobber': True, 'diskless': False, 'persist': False, 'format': 'NETCDF4'})>
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 210, in __del__
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 184, in close
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/contextlib.py", line 159, in helper
TypeError: 'NoneType' object is not callableTraceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/IPython/core/completer.py", line 174, in <module>
    names.append(unicodedata.name(chr(c)))
ValueError: no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/bin/panel", line 11, in <module>
    load_entry_point('panel==0.6.0', 'console_scripts', 'panel')()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/cli.py", line 41, in main
    bokeh_entry_point()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/__main__.py", line 64, in main
    _main(sys.argv)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/command/bootstrap.py", line 113, in main
    args.invoke(args)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/command/subcommands/serve.py", line 546, in invoke
    applications = build_single_handler_applications(args.files, argvs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/command/util.py", line 167, in build_single_handler_applications
    application = build_single_handler_application(path, argvs.get(path, []))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/command/util.py", line 124, in build_single_handler_application
    handler = NotebookHandler(filename=path, argv=argv)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/application/handlers/notebook.py", line 125, in __init__
    source, _ = exporter.from_notebook_node(nb)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 314, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/python.tpl", line 14, in root
    {% block input %}
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 11, in root
    
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 28, in block_body
    {%- block any_cell scoped -%}
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 42, in block_any_cell
    {%- if resources.global_content_filter.include_output_prompt -%}
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 68, in block_codecell
    {%- block traceback_line scoped -%}{%- endblock traceback_line -%}
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 82, in block_input_group
    {%- endif -%}
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/exporters/../templates/python.tpl", line 46, in block_input
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/nbconvert/filters/strings.py", line 204, in ipython2python
    from IPython.core.inputsplitter import IPythonInputSplitter
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 33, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/IPython/core/completer.py", line 174, in <module>
    names.append(unicodedata.name(chr(c)))
KeyboardInterrupt
2019-07-01 15:09:42,137 Starting Bokeh server version 1.2.0 (running on Tornado 6.0.3)
2019-07-01 15:09:42,143 Starting 6 processes
2019-07-01 15:09:42,152 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:09:42,153 Starting Bokeh server with process id: 24814
2019-07-01 15:09:42,153 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:09:42,154 Starting Bokeh server with process id: 24815
2019-07-01 15:09:42,155 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:09:42,155 Starting Bokeh server with process id: 24816
2019-07-01 15:09:42,156 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:09:42,157 Starting Bokeh server with process id: 24817
2019-07-01 15:09:42,158 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:09:42,158 Starting Bokeh server with process id: 24818
2019-07-01 15:09:42,160 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:09:42,160 Starting Bokeh server with process id: 24819
2019-07-01 15:10:26,810 101 GET /10-demo-FLDAS-dashbord-v2/ws?bokeh-protocol-version=1.0&bokeh-session-id=vm4qqkFYXeSKCBevYH1FG1XaCgY73YyE80nykW3qKjZa (127.0.0.1) 1.96ms
2019-07-01 15:10:26,810 WebSocket connection opened
2019-07-01 15:10:41,983 302 GET / (127.0.0.1) 1.23ms
2019-07-01 15:11:17,144 child 5 (pid 24819) killed by signal 11, restarting
2019-07-01 15:11:17,153 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-01 15:11:17,154 Starting Bokeh server with process id: 25154
2019-07-01 15:12:17,345 101 GET /10-demo-FLDAS-dashbord-v2/ws?bokeh-protocol-version=1.0&bokeh-session-id=AwMApVoSY2Z5YM46MlD1aszh1UmtDDJzlabGWZYfhDbw (::1) 2.08ms
2019-07-01 15:12:17,345 WebSocket connection opened
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (29.876657946863073, 12.864382106986772, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (29.876657946863073, 12.864382106986772, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (40.3180487223808, 4.125258893708734, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (40.3180487223808, 4.125258893708734, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (27.77775597893485, -1.9543239630701348, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (27.77775597893485, -1.9543239630701348, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (36.40750709382321, -6.414445978039508, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (36.40750709382321, -6.414445978039508, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (28.633252485343153, -8.506548012171868, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.633252485343153, -8.506548012171868, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  [6]
Callback from the scatter plot is called. Selected indices:  [17]
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: SoilTemp40_100cm_tavg
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: SoilTemp40_100cm_tavg
Getting a new timg...
-- Time: 2019-04-05T00:00:00.000000000, Region: EA, Variable: SoilTemp40_100cm_tavg
Getting a new timg...
-- Time: 2019-04-12T00:00:00.000000000, Region: EA, Variable: SoilTemp40_100cm_tavg
Getting a new timg...
-- Time: 2019-04-16T00:00:00.000000000, Region: EA, Variable: SoilTemp40_100cm_tavg
Getting a new timg...
-- Time: 2019-04-20T00:00:00.000000000, Region: EA, Variable: SoilTemp40_100cm_tavg
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-03T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-05T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-06T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-07T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-08T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-10T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-11T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Getting a new timg...
-- Time: 2019-04-12T00:00:00.000000000, Region: EA, Variable: Swnet_tavg
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called2019-07-02 11:01:25,952 200 GET /static/js/bokeh.min.js?v=1bfbafacfa847bc6589a4af73a904fef (127.0.0.1) 73.79ms
2019-07-02 11:01:25,952 200 GET /static/css/bokeh.min.css?v=8a37df7874e86834c87075ee096f36b7 (127.0.0.1) 72.98ms
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
2019-07-02 11:04:29,129 child 3 (pid 24817) killed by signal 11, restarting
2019-07-02 11:04:29,383 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-02 11:04:29,385 Starting Bokeh server with process id: 29938
2019-07-02 11:06:01,969 101 GET /10-demo-FLDAS-dashbord-v2/ws?bokeh-protocol-version=1.0&bokeh-session-id=6H57PTPZK3BGenuOyJ706HIH7W8joisv8wW7Imezs7nU (127.0.0.1) 14.84ms
2019-07-02 11:06:01,969 WebSocket connection opened
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (48.394065230475086, 10.006602757429821, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (48.394065230475086, 10.006602757429821, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (29.423391494922182, 12.499928093666611, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (29.423391494922182, 12.499928093666611, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (27.351722596654486, -0.30910200498508933, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (27.351722596654486, -0.30910200498508933, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (31.38348207941994, 10.98506994663213, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.38348207941994, 10.98506994663213, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (31.117705949380777, 13.604666288465316, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.117705949380777, 13.604666288465316, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (38.75448503497045, 7.270539301164148, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (38.75448503497045, 7.270539301164148, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (28.58086603907762, -6.025312727495957, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.58086603907762, -6.025312727495957, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (38.735228448363856, 4.82168637195287, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (38.735228448363856, 4.82168637195287, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (36.14354787982528, 7.404792982092386, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (36.14354787982528, 7.404792982092386, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (28.509098947876968, -3.404840385251781, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.509098947876968, -3.404840385251781, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (36.06594719975487, -7.077925240439195, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (36.06594719975487, -7.077925240439195, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  [24]
Callback from the scatter plot is called. Selected indices:  [23]
Callback from the scatter plot is called. Selected indices:  [16]
Callback from the scatter plot is called. Selected indices:  [25]
Callback from the scatter plot is called. Selected indices:  [27]
cb_tseries is called. x,y: (45.69170523025535, 6.299539340213186, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (45.69170523025535, 6.299539340213186, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (25.81822685663686, -6.5553771545794355, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (25.81822685663686, -6.5553771545794355, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  [1]
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (33.12360722487365, 13.051124901628855, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (33.12360722487365, 13.051124901628855, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (28.51026812708082, -7.637478056990662, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.51026812708082, -7.637478056990662, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean2019-07-02 11:49:34,357 200 GET /static/js/bokeh-tables.min.js?v=e840bf73f9fef1bffb5540a1aab13c0d (::1) 37.95ms
2019-07-02 11:52:22,199 child 4 (pid 24818) killed by signal 11, restarting
2019-07-02 11:52:22,754 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-02 11:52:22,758 Starting Bokeh server with process id: 1257
2019-07-07 15:30:48,251 child 5 (pid 25154) killed by signal 9, restarting
2019-07-07 15:30:49,830 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 15:30:49,834 Starting Bokeh server with process id: 19772
2019-07-07 22:16:34,858 302 GET / (127.0.0.1) 119.60ms
2019-07-07 22:17:00,527 200 GET /static/css/bokeh.min.css?v=8a37df7874e86834c87075ee096f36b7 (127.0.0.1) 8.08ms
2019-07-07 22:17:00,568 200 GET /static/css/bokeh-widgets.min.css?v=5fb15c2fc1344abfe5fa3615a34beae7 (::1) 0.92ms
2019-07-07 22:17:00,603 200 GET /static/js/bokeh.min.js?v=1bfbafacfa847bc6589a4af73a904fef (::1) 3.31ms
2019-07-07 22:17:01,015 200 GET /static/js/bokeh-widgets.min.js?v=d568632a768b6d5e0dcc8c423778d737 (127.0.0.1) 1.35ms
2019-07-07 22:17:01,078 200 GET /static/js/bokeh-tables.min.js?v=e840bf73f9fef1bffb5540a1aab13c0d (::1) 1.62ms
2019-07-07 22:17:01,130 200 GET /static/js/bokeh-gl.min.js?v=237dac0049e0a21220ba02fa552173a1 (127.0.0.1) 1.07ms
2019-07-07 22:17:01,334 101 GET /10-demo-FLDAS-dashbord-v2/ws?bokeh-protocol-version=1.0&bokeh-session-id=Z4SxHUK5KcHXEvYKOGU4TpdxUvThLxi2D5Rq7uFExtpk (::1) 1.29ms
2019-07-07 22:17:01,335 WebSocket connection opened
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7faa9f970f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (36.32804759476467, 7.047169258827415, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (36.32804759476467, 7.047169258827415, 'EA', 'Evap_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (35.36304013784478, 9.937411221501907, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.36304013784478, 9.937411221501907, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (30.34750115786406, 4.950385830084102, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (30.34750115786406, 4.950385830084102, 'EA', 'Evap_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (31.462065375637547, 3.9909039802549535, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.462065375637547, 3.9909039802549535, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (31.462065375637547, 3.9909039802549535, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.462065375637547, 3.9909039802549535, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
cb_tseries is called. x,y: (31.462065375637547, 3.9909039802549535, 'EA', 'Rainf_f_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.462065375637547, 3.9909039802549535, 'EA', 'Rainf_f_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
cb_tseries is called. x,y: (31.462065375637547, 3.9909039802549535, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.462065375637547, 3.9909039802549535, 'EA', 'SoilTemp00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (34.62947931083376, 7.290918098387346, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (34.62947931083376, 7.290918098387346, 'EA', 'SoilTemp00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (25.81812940048524, -0.5865153952721456, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (25.81812940048524, -0.5865153952721456, 'EA', 'SoilTemp00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (44.93553483109662, 3.688591960492157, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (44.93553483109662, 3.688591960492157, 'EA', 'SoilTemp00_10cm_tavg')
	Updated self.tstats_table
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Callback from the scatter plot is called. Selected indices:  [20]
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-04T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-05T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-06T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-07T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-08T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-09T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-10T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-12T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-13T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-14T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Received signal 15, shutting down
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Received signal 15, shutting down
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Received signal 15, shutting down
Received signal 15, shutting down
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
cb_tseries is called. x,y: (30.785138052824042, 17.61922906731187, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (30.785138052824042, 17.61922906731187, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Received signal 15, shutting down
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'SM01_Percentile')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'SM01_Percentile')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (30.00248620955482, 7.212996827100887, 'EA', 'SM01_Percentile')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (30.00248620955482, 7.212996827100887, 'EA', 'SM01_Percentile')
	Updated self.tstats_table
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
cb_tseries is called. x,y: (30.00248620955482, 7.212996827100887, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (30.00248620955482, 7.212996827100887, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (31.383300251585688, 12.225163096385957, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (31.383300251585688, 12.225163096385957, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (41.24187073739251, 3.9786501946364923, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (41.24187073739251, 3.9786501946364923, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (25.136503990427702, 9.630756197249035, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (25.136503990427702, 9.630756197249035, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (28.044671840167318, -0.11802930454726426, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.044671840167318, -0.11802930454726426, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (37.31869951067819, -0.3895559524807907, 'EA', 'SoilMoi10_40cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (37.31869951067819, -0.3895559524807907, 'EA', 'SoilMoi10_40cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  [21]
Callback from the scatter plot is called. Selected indices:  [18]
Callback from the scatter plot is called. Selected indices:  [29]
Callback from the scatter plot is called. Selected indices:  []
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-04T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-05T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-06T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-08T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-11T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-12T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-13T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-14T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-15T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-18T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-21T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-24T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-26T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: SoilTemp00_10cm_tavg
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-03T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-04T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-05T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-07T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-08T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-10T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Getting a new timg...
-- Time: 2019-04-11T00:00:00.000000000, Region: EA, Variable: SoilMoi100_200cm_tavg
Received signal 15, shutting down
2019-07-07 23:41:32,165 Starting Bokeh server version 1.2.0 (running on Tornado 6.0.3)
2019-07-07 23:41:32,170 Starting 6 processes
2019-07-07 23:41:32,180 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 23:41:32,180 Starting Bokeh server with process id: 3546
2019-07-07 23:41:32,180 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 23:41:32,180 Starting Bokeh server with process id: 3547
2019-07-07 23:41:32,182 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 23:41:32,182 Starting Bokeh server with process id: 3548
2019-07-07 23:41:32,183 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 23:41:32,183 Starting Bokeh server with process id: 3549
2019-07-07 23:41:32,185 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 23:41:32,185 Starting Bokeh server with process id: 3550
2019-07-07 23:41:32,186 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-07 23:41:32,187 Starting Bokeh server with process id: 3551
2019-07-07 23:41:54,357 101 GET /10-demo-FLDAS-dashbord-v2/ws?bokeh-protocol-version=1.0&bokeh-session-id=SDjJdQW80q5KzMG5GM5nNQs9gOYIkm0iOOaGsTyr3Uxj (::1) 1.95ms
2019-07-07 23:41:54,357 WebSocket connection opened
2019-07-07 23:43:51,685 101 GET /10-demo-FLDAS-dashbord-v2/ws?bokeh-protocol-version=1.0&bokeh-session-id=wZ4KDnBPWDFaFEb5NdcCzqHUP5FjQGR8JI9GdymKycro (127.0.0.1) 1.98ms
2019-07-07 23:43:51,685 WebSocket connection opened
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5967c94f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Getting a new timg...
-- Time: 2019-04-03T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (39.40150368020271, 1.6353769593883727, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (39.40150368020271, 1.6353769593883727, 'EA', 'Evap_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (28.797304386681994, 8.25985245356435, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.797304386681994, 8.25985245356435, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (28.797304386681994, 8.25985245356435, 'EA', 'SoilMoi00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.797304386681994, 8.25985245356435, 'EA', 'SoilMoi00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
cb_tseries is called. x,y: (28.797304386681994, 8.25985245356435, 'EA', 'SoilTemp40_100cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (28.797304386681994, 8.25985245356435, 'EA', 'SoilTemp40_100cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5967c94f28>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable",)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable

Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (29.80686048673216, -1.9541313392613109, 'EA', 'SoilTemp40_100cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (29.80686048673216, -1.9541313392613109, 'EA', 'SoilTemp40_100cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (37.41238581640049, -0.3782496632708218, 'EA', 'SoilTemp40_100cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (37.41238581640049, -0.3782496632708218, 'EA', 'SoilTemp40_100cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  [7]
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Callback from the scatter plot is called. Selected indices:  []
Callback from the scatter plot is called. Selected indices:  [7]
Callback from the scatter plot is called. Selected indices:  [29]
Callback from the scatter plot is called. Selected indices:  [15]
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Getting a new timg...
-- Time: 2019-04-06T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: Psurf_f_tavg
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: SM01_Percentile
Getting a new timg...
-- Time: 2019-04-02T00:00:00.000000000, Region: EA, Variable: SM01_Percentile
Getting a new timg...
-- Time: 2019-04-07T00:00:00.000000000, Region: EA, Variable: SM01_Percentile
Getting a new timg...
-- Time: 2019-04-10T00:00:00.000000000, Region: EA, Variable: SM01_Percentile
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'SoilTemp00_10cm_tavg')
	Updated self.tstats_table
Callback from the scatter plot is called. Selected indices:  []
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (29.151254965376406, 9.508412337393864, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (29.151254965376406, 9.508412337393864, 'EA', 'SoilTemp00_10cm_tavg')
	Updated self.tstats_table
cb_tseries is called. x,y: (33.719268281109485, 8.002313139843613, 'EA', 'SoilTemp00_10cm_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (33.719268281109485, 8.002313139843613, 'EA', 'SoilTemp00_10cm_tavg')2019-07-08 02:30:51,159 child 5 (pid 3551) killed by signal 9, restarting
2019-07-08 02:30:52,017 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-08 02:30:52,020 Starting Bokeh server with process id: 22599
2019-07-08 09:22:16,237 302 GET / (::1) 1.84ms
2019-07-08 11:04:02,491 302 GET / (::1) 26.30ms
2019-07-08 11:05:42,849 child 4 (pid 3550) killed by signal 11, restarting
2019-07-08 11:05:43,280 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-08 11:05:43,281 Starting Bokeh server with process id: 1064
2019-07-08 13:48:07,044 302 GET / (::1) 73.44ms
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5967c94f28>>, <Future finished exception=AbbreviatedException(<class 'ValueError'>, ValueError('Out of range float values are not JSON compliant',), <traceback object at 0x7f592025d108>)>)
Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1303, in _update_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, data)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1168, in _update_glyph
    glyph.update(**update)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/has_props.py", line 376, in update
    setattr(self, k, v)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 545, in __set__
    self._internal_set(obj, value, setter=setter)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 769, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 838, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 915, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/model.py", line 704, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 161, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1005, in _notify_change
    self._trigger_on_change(event)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1100, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1099, in invoke_callbacks
    cb(event)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 669, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/events.py", line 244, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/events.py", line 126, in dispatch
    receiver._document_patched(self)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 223, in _document_patched
    self._pending_writes.append(connection.send_patch_document(event))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/connection.py", line 76, in send_patch_document
    msg = self.protocol.create('PATCH-DOC', [event])
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/protocol/__init__.py", line 80, in create
    return self._messages[msgtype].create(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 93, in create
    patch_json, buffers = process_document_events(events, use_buffers)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 136, in process_document_events
    return serialize_json(json), buffers if use_buffers else []
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/core/json_encoder.py", line 161, in serialize_json
    return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/callbacks.py", line 362, in process_on_event
    self.on_msg(msg)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/callbacks.py", line 134, in on_msg
    raise e
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/callbacks.py", line 132, in on_msg
    Stream.trigger(streams)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/streams.py", line 158, in trigger
    subscriber(**dict(union))
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/plot.py", line 184, in refresh
    super(BokehPlot, self).refresh(**kwargs)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/plot.py", line 615, in refresh
    self._trigger_refresh(stream_key)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/plot.py", line 624, in _trigger_refresh
    self.update(key)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/plot.py", line 596, in update
    item = self.__getitem__(key)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/plot.py", line 261, in __getitem__
    self.update_frame(frame)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 2168, in update_frame
    subplot.update_frame(key, ranges, element=el)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1354, in update_frame
    self._update_glyphs(element, ranges, self.style[self.cyclic_index])
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/plotting/bokeh/element.py", line 1303, in _update_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, data)
  File "/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/holoviews/core/options.py", line 200, in __exit__
    raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: ValueError: Out of range float values are not JSON compliant

To view the original traceback, catch this exception and call print_traceback() method.
2019-07-08 14:30:51,251 child 5 (pid 22599) killed by signal 9, restarting
2019-07-08 14:30:51,296 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-08 14:30:51,297 Starting Bokeh server with process id: 18192
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Received signal 15, shutting down
2019-07-24 01:37:53,039 child 3 (pid 3549) exited normally
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
Parameter name clashes for keys {'x_range', 'y_range'}
cb_tseries is called. x,y: (44.92535375325445, 11.289824127969055, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Received signal 15, shutting down
2019-07-24 01:38:51,247 child 4 (pid 1064) killed by signal 6, restarting
2019-07-24 01:38:51,603 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-24 01:38:51,605 Starting Bokeh server with process id: 5520
/home/hayley/miniconda3/envs/earthml/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Parameter name clashes for keys {'x_range', 'y_range'}
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: SM01_Percentile
Added /home/hayley/Playground/InteractML/examples/tutorial/../utils to sys.path
Currently available renderers:  bokeh
Psurf_f_tavg
Selecting a datavariable at a fixed time point:  2019-04-05 Qg_tavg
<xarray.DataArray 'Qg_tavg' (Y: 348, X: 294)>
dask.array<shape=(348, 294), dtype=float32, chunksize=(348, 294)>
Coordinates:
  * X        (X) float64 22.05 22.15 22.25 22.35 ... 51.05 51.15 51.25 51.35
  * Y        (Y) float64 -11.75 -11.65 -11.55 -11.45 ... 22.65 22.75 22.85 22.95
    time     datetime64[ns] 2019-04-04
Attributes:
    standard_name:  downward_heat_flux_in_soil
    long_name:      soil heat flux
    units:          W m-2
    vmin:           -1000000000000000.0
    vmax:           1000000000000000.0
    cell_methods:   time:mean
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Created initial tap and selection1d stream instances...
Initialing a debug box...
Initiated debug_dmap with current streams to debug_box
Setting main plot dynamically...
	Time:  2019-04-01 00:00:00 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Update is called
Converting timevalues to python datetime object
get_empty_tplot is called
Finished updating xrd, time_values, empty_tplot, dmap_vlines)
Getting a new main img...
	Time: 2019-04-01 00:00:00, Region: EA
Callback from the scatter plot is called. Selected indices:  []
cb_tseries is called. x,y: (35.0, 0.0, 'EA', 'Evap_tavg')"
	self.scatter is updated
	self.sel_stream's source is changed to the new self.tscatter object
cb_tstats is called: (35.0, 0.0, 'EA', 'Evap_tavg')
	Updated self.tstats_table
Getting a new timg...
-- Time: 2019-04-01T00:00:00.000000000, Region: EA, Variable: RadT_tavg
Received signal 15, shutting down
2019-07-24 01:41:16,153 child 2 (pid 3548) killed by signal 6, restarting
2019-07-24 01:41:16,163 Bokeh app running at: http://localhost:5006/10-demo-FLDAS-dashbord-v2
2019-07-24 01:41:16,163 Starting Bokeh server with process id: 5770
